```js
try {
  await auth.init()
} catch (e) {
  // Handle exception case
}
```
